spring:
  application:
    name: rabbitmq-consumer
  rabbitmq:
    host: 192.168.213.130
    port: 5672
    username: rabbit
    password: 123456
    publisher-confirms: true
    virtual-host: /


server:
  port: 8081